name: "publish"

on:
    push:
        branches: 
          - master

jobs:
    build:
      name: test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

    release:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2.1.1
            - name: node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}