name: CD

on:
    pull_request:
        branches: [master]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
                  registry-url: https://registry.npmjs.org
            - name: Publish
            - run: npm install
            - run: npm run build --if-present
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
