name: 'CD'

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1
            - name: Setup Node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
            - run: npm install
            - run: npm run build --if-present
            - run: npm test

    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.1.1
            - name: Setup Node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: Publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
